<?php if ( ! defined( 'ABSPATH' ) ) { exit; }
$employee = LM_AI_Office_Animations::EMPLOYEE; $actions = LM_AI_Office_Animations::actions(); $assets = LM_AI_Office_Animations::assets( $employee ); $notice = sanitize_text_field( wp_unslash( $_GET['animation_notice'] ?? '' ) );
?>
<div class="wrap lm-ai-office-admin lm-ai-office-animation-library"><h1>Thư viện chuyển động</h1>
<?php if ( $notice ) : ?><div class="notice notice-info is-dismissible"><p><?php echo esc_html( $notice ); ?></p></div><?php endif; ?>
<section class="lm-ai-office-panel"><label for="lm-ai-office-character"><strong>Thư viện dùng chung:</strong></label> <select id="lm-ai-office-character"><option value="employee_001">Employee 001</option></select><p>Chỉ nhận tệp FBX, GLB hoặc GLTF từ Media Library. Animation lưu ở đây sẽ dùng cho Employee 001 và tự làm fallback cho Claudia 002 nếu nhân vật nữ chưa có animation riêng.</p></section>
<div class="lm-ai-office-animation-list">
<?php foreach ( $actions as $key => $action ) : $variants = $assets[ $key ] ?? array(); ?>
<article class="lm-ai-office-animation-card"><h2><?php echo esc_html( $action['label'] ); ?></h2><p><?php echo esc_html( $action['description'] ); ?></p>
<p><strong>Trạng thái:</strong> <?php echo esc_html( $variants ? 'Sẵn sàng' : 'Chưa có chuyển động' ); ?></p>
<?php if ( $variants ) : ?><ul><?php foreach ( $variants as $index => $asset ) : ?><li><strong><?php echo esc_html( $asset['label'] ?? 'Animation' ); ?></strong> · <?php echo esc_html( strtoupper( $asset['format'] ?? '' ) ); ?> · Chuyển xương: <?php echo esc_html( 'compatible' === ( $asset['retarget_status'] ?? '' ) ? 'Tương thích' : 'Chưa kiểm tra' ); ?>
<button type="button" class="button button-small" data-animation-preview data-animation-url="<?php echo esc_url( $asset['url'] ?? '' ); ?>" data-animation-clip="<?php echo esc_attr( $asset['clip'] ?? '' ); ?>" data-animation-label="<?php echo esc_attr( $action['label'] ); ?>">Xem thử</button>
<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="lm-ai-office-inline-form"><?php wp_nonce_field( 'lm_ai_office_animation_remove' ); ?><input type="hidden" name="action" value="lm_ai_office_animation_remove"><input type="hidden" name="employee" value="employee_001"><input type="hidden" name="action_key" value="<?php echo esc_attr( $key ); ?>"><input type="hidden" name="variant_index" value="<?php echo esc_attr( $index ); ?>"><button class="button button-small" type="submit">Xóa</button></form></li><?php endforeach; ?></ul><?php endif; ?>
<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="lm-ai-office-animation-upload"><?php wp_nonce_field( 'lm_ai_office_animation_add' ); ?><input type="hidden" name="action" value="lm_ai_office_animation_add"><input type="hidden" name="employee" value="employee_001"><input type="hidden" name="action_key" value="<?php echo esc_attr( $key ); ?>"><input type="hidden" name="attachment_id" value="" data-animation-attachment><button type="button" class="button" data-animation-select><?php echo esc_html( $variants ? 'Thay thế / thêm tệp' : 'Tải tệp lên' ); ?></button> <span data-animation-file>Chưa chọn tệp</span> <button type="submit" class="button button-primary" disabled>Lưu</button></form>
</article><?php endforeach; ?>
</div><div class="lm-ai-office-animation-preview" data-animation-preview-modal hidden><div class="lm-ai-office-animation-preview__dialog"><button type="button" class="button-link" data-animation-preview-close>Đóng</button><h2 data-animation-preview-title>Xem thử chuyển động</h2><p data-animation-preview-status>Đang tải…</p><div class="lm-ai-office-animation-preview__canvas" data-animation-preview-canvas></div><div class="lm-ai-office-animation-preview__controls" aria-label="Điều khiển góc xem"><button type="button" class="button" data-animation-preview-control="rotate-left">Xoay trái</button><button type="button" class="button" data-animation-preview-control="rotate-right">Xoay phải</button><button type="button" class="button" data-animation-preview-control="zoom-in">Phóng to</button><button type="button" class="button" data-animation-preview-control="zoom-out">Thu nhỏ</button><button type="button" class="button" data-animation-preview-control="reset">Đặt lại góc nhìn</button></div><p class="description">Bạn cũng có thể kéo trực tiếp trên nhân vật để xoay và lăn chuột để phóng to hoặc thu nhỏ.</p></div></div></div>
