<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<style>
/* Render after enqueued styles so the task panel is hidden until its button is pressed. */
#<?php echo esc_attr( $config['id'] ); ?> .dat-ai-office__task-modal[hidden],
#<?php echo esc_attr( $config['id'] ); ?> .dat-ai-office__agent-card[hidden] { display: none !important; }
</style>
<section id="<?php echo esc_attr( $config['id'] ); ?>" class="dat-ai-office dat-ai-office--<?php echo esc_attr( $config['theme'] ); ?>" style="--dat-ai-office-height:<?php echo esc_attr( $config['height'] ); ?>px" data-office-config="<?php echo esc_attr( wp_json_encode( $config ) ); ?>">
	<div class="dat-ai-office__stage" aria-label="Mô phỏng văn phòng số AI"></div>
	<?php if ( $config['showDashboard'] ) : ?><aside class="dat-ai-office__dashboard" data-office-dashboard><button type="button" class="dat-ai-office__collapse" data-office-toggle="dashboard" aria-label="Ẩn dashboard">×</button><span class="dat-ai-office__eyebrow">LIVE OPERATIONS</span><h2><?php echo esc_html( $config['data']['settings']['model_name'] ); ?></h2><div class="dat-ai-office__metrics" data-office-metrics></div></aside><?php endif; ?>
	<?php if ( $config['showLog'] ) : ?><aside class="dat-ai-office__log" data-office-log><div class="dat-ai-office__log-head"><b>Nhật ký hoạt động</b><button type="button" data-office-toggle="log">×</button></div><select data-office-filter><option value="all">Tất cả</option><option value="sales">Sale</option><option value="pcb">Kỹ thuật</option><option value="smt">Sản xuất</option><option value="qc">QC</option><option value="warehouse">Kho</option><option value="finance">Kế toán</option><option value="ai">AI</option></select><div class="dat-ai-office__log-list" data-office-log-list></div></aside><?php endif; ?>
	<div class="dat-ai-office__agent-card" data-office-agent-card hidden></div>
	<?php if ( $config['canManage'] ) : ?><div class="dat-ai-office__task-modal" data-office-task-modal hidden><form data-office-task-form><button type="button" data-office-close-task aria-label="Đóng">×</button><h3>Giao nhiệm vụ</h3><label>Tên nhiệm vụ<input required name="title" maxlength="190"></label><label>Mô tả<textarea name="description"></textarea></label><label>Phòng ban<select name="department" data-office-departments></select></label><label>Người nhận<select name="assignee" data-office-assignees></select></label><label>Ưu tiên<select name="priority"><option value="normal">Bình thường</option><option value="high">Cao</option><option value="critical">Khẩn</option></select></label><label>Workflow<select name="workflow_key" data-office-workflows></select></label><button class="dat-ai-office__primary" type="submit">Bắt đầu giao việc</button></form></div><?php endif; ?>
	<?php if ( $config['showControls'] ) : ?><nav class="dat-ai-office__controls" aria-label="Điều khiển văn phòng"><button type="button" data-office-action="zoom-in">＋</button><button type="button" data-office-action="zoom-out">－</button><button type="button" data-office-action="reset">⌂</button><button type="button" data-office-action="tour">◎</button><button type="button" data-office-action="fullscreen">⛶</button><?php if ( $config['canManage'] ) : ?><button type="button" data-office-action="task">Giao nhiệm vụ</button><?php endif; ?><button type="button" data-office-action="sound">Âm thanh</button></nav><?php endif; ?>
</section>
