<?php $field = DAT_AI_OFFICE_OPTION; ?>
<table class="form-table" role="presentation"><tbody>
<tr><th><label>Tên công ty</label></th><td><input class="regular-text" name="<?php echo esc_attr( $field ); ?>[company_name]" value="<?php echo esc_attr( $settings['company_name'] ); ?>"></td></tr>
<tr><th><label>Tên mô hình</label></th><td><input class="regular-text" name="<?php echo esc_attr( $field ); ?>[model_name]" value="<?php echo esc_attr( $settings['model_name'] ); ?>"></td></tr>
<tr><th><label>Màu nền / UI</label></th><td><input type="color" name="<?php echo esc_attr( $field ); ?>[background_color]" value="<?php echo esc_attr( $settings['background_color'] ); ?>"> <input type="color" name="<?php echo esc_attr( $field ); ?>[ui_color]" value="<?php echo esc_attr( $settings['ui_color'] ); ?>"></td></tr>
<tr><th><label>Hiệu năng</label></th><td>Số nhân vật tối đa <input type="number" min="4" max="80" name="<?php echo esc_attr( $field ); ?>[max_agents]" value="<?php echo esc_attr( $settings['max_agents'] ); ?>"> &nbsp; Tốc độ <input type="number" min="0.25" max="3" step="0.25" name="<?php echo esc_attr( $field ); ?>[animation_speed]" value="<?php echo esc_attr( $settings['animation_speed'] ); ?>"> &nbsp; FPS <select name="<?php echo esc_attr( $field ); ?>[fps_max]"><?php foreach ( array( 30, 45, 60 ) as $fps ) : ?><option value="<?php echo esc_attr( $fps ); ?>" <?php selected( $settings['fps_max'], $fps ); ?>><?php echo esc_html( $fps ); ?></option><?php endforeach; ?></select></td></tr>
<tr><th><label>Hiển thị</label></th><td><?php foreach ( array( 'dashboard_enabled' => 'Dashboard', 'log_enabled' => 'Nhật ký', 'auto_camera' => 'Camera tự động', 'day_night_enabled' => 'Ngày/đêm', 'sound_enabled' => 'Âm thanh', 'low_performance' => 'Low Performance', 'show_names' => 'Tên nhân vật', 'show_bubbles' => 'Bong bóng chat', 'debug' => 'Chế độ Debug' ) as $key => $label ) : ?><label class="dat-ai-office-check"><input type="checkbox" name="<?php echo esc_attr( $field ); ?>[<?php echo esc_attr( $key ); ?>]" value="1" <?php checked( $settings[ $key ] ); ?>> <?php echo esc_html( $label ); ?></label><?php endforeach; ?></td></tr>
<tr><th><label>Xóa dữ liệu</label></th><td><label><input type="checkbox" name="<?php echo esc_attr( $field ); ?>[delete_on_uninstall]" value="1" <?php checked( $settings['delete_on_uninstall'] ); ?>> Xóa toàn bộ dữ liệu khi gỡ plugin</label></td></tr>
</tbody></table>
